import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "SE Next App",
  description: "Generated by create SEO",
  keywords: ["SEO", "Next.js"],
};

export default function ContactPage () {
  return (
    <div>Contact page</div>
  )
}
