import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "SE Next App",
  description: "Generated by create SEO",
};

export default function AboutPage() {
  return <div>page about</div>;
}
