import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "SE Next App",
  description: "Generated by create SEO",
  keywords: ["SEO", "Next.js"],
};
export default function PricingPage() {
  return <div>page pricing</div>;
}
